services:
  api:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/home/node/workspace:cached
      - node_modules:/home/node/workspace/node_modules


    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "chown -R node:node /home/node/workspace && while sleep 1000; do :; done"

volumes:
  node_modules:
